import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import RootProvider from '@/lib/RootProvider';
import { getCurrentLocale } from '@/locales/server';
import { Footer } from '@/widgets/Footer/Footer';
import Container from '@/shared/Container/Container';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: '/littleFoot.svg',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = getCurrentLocale();
  return (
    <html lang={locale}>
      <RootProvider>
        <body className={montserrat.className}>
          <main style={{ minHeight: '100vh' }}>{children}</main>
          <Footer />
        </body>
      </RootProvider>
    </html>
  );
}
