import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Provider from '@/lib/Provider';
import { getCurrentLocale } from '@/locales/server';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = getCurrentLocale();
  return (
    <html lang={locale}>
      <Provider>
        <body className={montserrat.className}>
          <main>{children}</main>
        </body>
      </Provider>
    </html>
  );
}
