import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import RootProvider from '@/lib/RootProvider';
import { getCurrentLocale } from '@/locales/server';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = getCurrentLocale();
  return (
    <RootProvider>
      <html lang={locale}>
        <body className={montserrat.className}>
          <main>{children}</main>
        </body>
      </html>
    </RootProvider>
  );
}
